// PDF export utility for Rwanda data and reports
import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Extend jsPDF type to include autoTable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

interface ExportOptions {
  title: string;
  subtitle?: string;
  data: any[];
  columns: Array<{
    header: string;
    dataKey: string;
    width?: number;
  }>;
  filename: string;
  orientation?: 'portrait' | 'landscape';
  pageSize?: 'A4' | 'A3' | 'letter';
}

export const exportToPDF = (options: ExportOptions): void => {
  const {
    title,
    subtitle,
    data,
    columns,
    filename,
    orientation = 'portrait',
    pageSize = 'A4'
  } = options;

  const doc = new jsPDF({
    orientation,
    unit: 'mm',
    format: pageSize
  });

  // Add header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 20, 30);

  if (subtitle) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(subtitle, 20, 40);
  }

  // Add Qivook branding
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by Qivook Trade Intelligence Platform', 20, 50);

  // Add timestamp
  const timestamp = new Date().toLocaleString();
  doc.text(`Generated on: ${timestamp}`, 20, 55);

  // Add data table
  doc.autoTable({
    startY: 65,
    head: [columns.map(col => col.header)],
    body: data.map(row => columns.map(col => row[col.dataKey] || '')),
    styles: {
      fontSize: 8,
      cellPadding: 3,
      overflow: 'linebreak',
      halign: 'left'
    },
    headStyles: {
      fillColor: [59, 130, 246], // Primary blue
      textColor: 255,
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251] // Light gray
    },
    columnStyles: columns.reduce((acc, col, index) => {
      if (col.width) {
        acc[index] = { cellWidth: col.width };
      }
      return acc;
    }, {} as any),
    margin: { left: 20, right: 20 }
  });

  // Add footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.width - 40,
      doc.internal.pageSize.height - 10
    );
    doc.text(
      'Data sourced from Logistics Cluster (logcluster.org)',
      20,
      doc.internal.pageSize.height - 10
    );
  }

  // Save the PDF
  doc.save(`${filename}.pdf`);
};

// Export Rwanda suppliers to PDF
export const exportRwandaSuppliersToPDF = (suppliers: any[]): void => {
  const columns = [
    { header: 'Name', dataKey: 'name', width: 40 },
    { header: 'Category', dataKey: 'category', width: 20 },
    { header: 'Location', dataKey: 'location', width: 30 },
    { header: 'Phone', dataKey: 'contact.phone', width: 25 },
    { header: 'Email', dataKey: 'contact.email', width: 35 },
    { header: 'Verified', dataKey: 'verified', width: 15 },
    { header: 'Rating', dataKey: 'rating', width: 15 }
  ];

  exportToPDF({
    title: 'Rwanda Suppliers Directory',
    subtitle: 'Complete list of verified suppliers and service providers',
    data: suppliers,
    columns,
    filename: 'rwanda-suppliers',
    orientation: 'landscape'
  });
};

// Export Rwanda government contacts to PDF
export const exportRwandaGovernmentToPDF = (contacts: any[]): void => {
  const columns = [
    { header: 'Ministry', dataKey: 'ministry', width: 35 },
    { header: 'Name', dataKey: 'name', width: 25 },
    { header: 'Title', dataKey: 'title', width: 25 },
    { header: 'Phone', dataKey: 'contact.phone', width: 20 },
    { header: 'Email', dataKey: 'contact.email', width: 30 },
    { header: 'Website', dataKey: 'contact.website', width: 25 }
  ];

  exportToPDF({
    title: 'Rwanda Government Contacts',
    subtitle: 'Ministry and department contact information',
    data: contacts,
    columns,
    filename: 'rwanda-government-contacts',
    orientation: 'landscape'
  });
};

// Export Rwanda infrastructure to PDF
export const exportRwandaInfrastructureToPDF = (infrastructure: any[]): void => {
  const columns = [
    { header: 'Facility', dataKey: 'name', width: 30 },
    { header: 'Type', dataKey: 'type', width: 20 },
    { header: 'Location', dataKey: 'location', width: 25 },
    { header: 'Status', dataKey: 'status', width: 15 },
    { header: 'Capacity', dataKey: 'capacity', width: 20 },
    { header: 'Phone', dataKey: 'contact.phone', width: 20 },
    { header: 'Email', dataKey: 'contact.email', width: 30 }
  ];

  exportToPDF({
    title: 'Rwanda Infrastructure Overview',
    subtitle: 'Logistics infrastructure and facilities',
    data: infrastructure,
    columns,
    filename: 'rwanda-infrastructure',
    orientation: 'landscape'
  });
};

// Export Rwanda pricing to PDF
export const exportRwandaPricingToPDF = (pricing: any[]): void => {
  const columns = [
    { header: 'Category', dataKey: 'category', width: 20 },
    { header: 'Item', dataKey: 'item', width: 30 },
    { header: 'Price', dataKey: 'price', width: 15 },
    { header: 'Currency', dataKey: 'currency', width: 15 },
    { header: 'Unit', dataKey: 'unit', width: 15 },
    { header: 'Source', dataKey: 'source', width: 25 },
    { header: 'Last Updated', dataKey: 'lastUpdated', width: 20 }
  ];

  exportToPDF({
    title: 'Rwanda Pricing Intelligence',
    subtitle: 'Current pricing data for fuel, labor, and transport',
    data: pricing,
    columns,
    filename: 'rwanda-pricing',
    orientation: 'portrait'
  });
};

// Export comprehensive Rwanda report
export const exportRwandaComprehensiveReport = (data: {
  suppliers: any[];
  government: any[];
  infrastructure: any[];
  pricing: any[];
  stats: any;
}): void => {
  const doc = new jsPDF('portrait', 'mm', 'A4');

  // Title page
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Rwanda Logistics Intelligence Report', 20, 40);

  doc.setFontSize(16);
  doc.setFont('helvetica', 'normal');
  doc.text('Comprehensive Logistics Data and Analysis', 20, 55);

  doc.setFontSize(12);
  doc.text('Generated by Qivook Trade Intelligence Platform', 20, 70);
  doc.text(`Generated on: ${new Date().toLocaleString()}`, 20, 80);

  // Executive Summary
  doc.addPage();
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', 20, 30);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  const summaryText = `
This report provides comprehensive logistics intelligence for Rwanda, including:
• ${data.stats.totalSuppliers} verified suppliers across multiple categories
• ${data.stats.governmentAgencies} government agencies and ministries
• ${data.stats.infrastructureFacilities} infrastructure facilities
• ${data.stats.pricingItems} pricing data points

Data is sourced from Logistics Cluster (logcluster.org) and verified through multiple channels.
  `;
  
  doc.text(summaryText, 20, 45, { maxWidth: 170 });

  // Suppliers section
  doc.addPage();
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Supplier Directory', 20, 30);

  const supplierColumns = [
    { header: 'Name', dataKey: 'name' },
    { header: 'Category', dataKey: 'category' },
    { header: 'Location', dataKey: 'location' },
    { header: 'Phone', dataKey: 'contact.phone' },
    { header: 'Email', dataKey: 'contact.email' }
  ];

  doc.autoTable({
    startY: 40,
    head: [supplierColumns.map(col => col.header)],
    body: data.suppliers.slice(0, 20).map(row => 
      supplierColumns.map(col => row[col.dataKey] || '')
    ),
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [59, 130, 246], textColor: 255, fontStyle: 'bold' }
  });

  // Government contacts section
  doc.addPage();
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Government Contacts', 20, 30);

  const governmentColumns = [
    { header: 'Ministry', dataKey: 'ministry' },
    { header: 'Name', dataKey: 'name' },
    { header: 'Title', dataKey: 'title' },
    { header: 'Phone', dataKey: 'contact.phone' },
    { header: 'Email', dataKey: 'contact.email' }
  ];

  doc.autoTable({
    startY: 40,
    head: [governmentColumns.map(col => col.header)],
    body: data.government.map(row => 
      governmentColumns.map(col => row[col.dataKey] || '')
    ),
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [59, 130, 246], textColor: 255, fontStyle: 'bold' }
  });

  // Infrastructure section
  doc.addPage();
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Infrastructure Overview', 20, 30);

  const infrastructureColumns = [
    { header: 'Facility', dataKey: 'name' },
    { header: 'Type', dataKey: 'type' },
    { header: 'Location', dataKey: 'location' },
    { header: 'Status', dataKey: 'status' },
    { header: 'Capacity', dataKey: 'capacity' }
  ];

  doc.autoTable({
    startY: 40,
    head: [infrastructureColumns.map(col => col.header)],
    body: data.infrastructure.map(row => 
      infrastructureColumns.map(col => row[col.dataKey] || '')
    ),
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [59, 130, 246], textColor: 255, fontStyle: 'bold' }
  });

  // Pricing section
  doc.addPage();
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Pricing Intelligence', 20, 30);

  const pricingColumns = [
    { header: 'Category', dataKey: 'category' },
    { header: 'Item', dataKey: 'item' },
    { header: 'Price', dataKey: 'price' },
    { header: 'Currency', dataKey: 'currency' },
    { header: 'Unit', dataKey: 'unit' }
  ];

  doc.autoTable({
    startY: 40,
    head: [pricingColumns.map(col => col.header)],
    body: data.pricing.map(row => 
      pricingColumns.map(col => row[col.dataKey] || '')
    ),
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [59, 130, 246], textColor: 255, fontStyle: 'bold' }
  });

  // Footer on all pages
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.width - 40,
      doc.internal.pageSize.height - 10
    );
    doc.text(
      'Data sourced from Logistics Cluster (logcluster.org)',
      20,
      doc.internal.pageSize.height - 10
    );
  }

  doc.save('rwanda-comprehensive-report.pdf');
};

// Utility function to format data for PDF export
export const formatDataForPDF = (data: any[], columns: string[]): any[] => {
  return data.map(item => {
    const formatted: any = {};
    columns.forEach(column => {
      const value = column.split('.').reduce((obj, key) => obj?.[key], item);
      formatted[column] = value || '';
    });
    return formatted;
  });
};

// Export current page content to PDF
export const exportCurrentPageToPDF = (): void => {
  const pageTitle = document.title || 'Qivook Report';
  const pageContent = document.body.innerText;
  
  const doc = new jsPDF();
  
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(pageTitle, 20, 30);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(pageContent, 20, 50, { maxWidth: 170 });
  
  doc.save(`${pageTitle.toLowerCase().replace(/\s+/g, '-')}.pdf`);
};

